# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [5]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [6]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.07217465 0.38031646 0.04785796 ... 0.91666128 0.48558327 0.10404636]
 [0.34859539 0.2904112  0.90700047 ... 0.33035206 0.65220594 0.86774011]
 [0.95335872 0.48555967 0.51215378 ... 0.59524852 0.59019053 0.59233792]
 ...
 [0.30683156 0.40208505 0.79264598 ... 0.31551311 0.34397807 0.12934296]
 [0.22267376 0.22235774 0.63345589 ... 0.59440718 0.10713786 0.42014017]
 [0.90374056 0.72650844 0.16416493 ... 0.97135087 0.90796932 0.57572619]]
[[0.54492258 0.54764819 0.21547595 ... 0.26984078 0.50612784 0.49475228]
 [0.29324551 0.82651484 0.8140269  ... 0.34910981 0.83280285 0.45877096]
 [0.05181835 0.38354599 0.90301951 ... 0.80805057 0.2731739  0.68310479]
 ...
 [0.32036574 0.86732782 0.42726156 ... 0.58015247 0.21739178 0.60711443]
 [0.37858433 0.18683068 0.88622626 ... 0.24606352 0.06250118 0.68173044]
 [0.06030616 0.74550722 0.91596284 ... 0.6031518  0.88542049 0.21806448]]


Без использования numpy

In [7]:
def mult(a, b):
    result = None
    n = len(a)
    m = len(b[0])
    result = [[0] * m for _ in range(n)]

    for i in range(n):
        for j in range(m):
            for k in range(n):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [8]:
def np_mult(a, b):
    result = None
    result = np.dot(a, b)
    return result

In [9]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.47 s, sys: 4.07 ms, total: 1.48 s
Wall time: 1.53 s


In [10]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.13 ms, sys: 1.04 ms, total: 3.17 ms
Wall time: 20.2 ms


In [11]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4988899010859313e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [13]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.48941821 0.43624245 0.13156283] [0.92105587 0.57826341 0.92502475]


In [14]:
def scalar_product(a,b):
    s = 0
    s = sum(x * y for x, y in zip(a, b))
    return s

In [15]:
def np_scalar_product(a,b):
    s = 0
    s = np.dot(a, b)
    return s

In [16]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 29 µs, sys: 4 µs, total: 33 µs
Wall time: 37.4 µs
CPU times: user 108 µs, sys: 14 µs, total: 122 µs
Wall time: 126 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы numpy реализуются быстрее из-за того, что методы библиотеки написаны на C и Fortran -> вычисления происходят на более низком уровне.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [19]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  n = len(a)
  diagonali = np.diag(a)
  even_diagonal = [x for x in diagonali if x % 2 == 0]
  if len(even_diagonal) > 0:
      return sum(even_diagonal)
  else:
      return 0

In [20]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 2, 5, 5, 9],
       [6, 6, 1, 7, 8],
       [7, 7, 2, 2, 1],
       [1, 4, 1, 3, 6],
       [5, 2, 3, 6, 2]])

In [21]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 56 µs, sys: 8 µs, total: 64 µs
Wall time: 68.2 µs


18

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [30]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cumulative_sums = np.cumsum(X, axis=1)
    result = cumulative_sums / np.arange(1, X.shape[1] + 1)
    return result

In [31]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[3.26208884e-01 3.20564496e-01 6.71930126e-01 4.00309524e-01
 4.80543749e-01 4.69295793e-02 1.94162229e-02 2.54475598e-01
 1.45833627e-01 5.05695225e-02 5.37784996e-01 3.50200968e-02
 5.37620615e-01 1.87390874e-01 4.69024176e-01 3.66381891e-01
 6.63409064e-01 6.01697891e-01 3.48867736e-01 7.06460595e-01
 2.38348309e-01 3.13519265e-01 5.59865424e-01 4.12343796e-02
 7.53500691e-01 1.44755721e-01 8.41638585e-01 3.82275707e-01
 5.77745303e-01 2.99472420e-01 5.36034646e-01 9.22361027e-02
 3.61898005e-01 9.89943019e-01 1.48907567e-01 2.90879089e-01
 8.91657896e-01 1.52816879e-01 3.17593725e-01 7.64122405e-02
 8.27944433e-01 1.17619163e-01 4.07875066e-01 5.20547496e-01
 1.13306094e-01 5.71499243e-01 4.88915492e-01 7.69399282e-01
 6.66398242e-01 4.48364808e-01 8.95372595e-01 9.43613205e-01
 7.97711910e-02 5.12024232e-01 1.74212146e-01 4.10613346e-01
 9.70557731e-01 3.65598851e-01 3.77442180e-01 2.02518528e-01
 5.75122266e-01 6.45596090e-01 2.77998305e-01 6.28595645e-01
 4.74698647e-01 8.059874

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [37]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = None
    if len(a) == 0:
        return np.array([]), np.array([])

    current_element = a[0]
    count = 1
    encoded_elements = []
    repetitions = []
    for element in a[1:]:
        if element == current_element:
            count += 1
        else:
            encoded_elements.append(current_element)
            repetitions.append(count)

            current_element = element
            count = 1
    encoded_elements.append(current_element)
    repetitions.append(count)
    return np.array(encoded_elements), np.array(repetitions)

In [40]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
np_encode(X)

CPU times: user 40 µs, sys: 6 µs, total: 46 µs
Wall time: 49.6 µs


(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))

### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [41]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    transformed_X = X.copy()

    transformed_X[1::2] = a

    transformed_X[::2] = transformed_X[::2] ** 3

    reversed_transformed_X = transformed_X[::-1]

    result = np.concatenate((X, reversed_transformed_X))

    return result

In [42]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 138 µs, sys: 19 µs, total: 157 µs
Wall time: 233 µs
